#!/bin/bash


if [[ $# -lt 5 ]]; then
    echo "Usage: $0 <smts> <script-dir> <output-dir> <config> <example1> [<example2> [ ... ] ]";
    exit 1;
fi

smts_server=$1; shift
script_dir=$1; shift
#work under linux
out_dir=`readlink -e $1`; shift

#work under mac
#out_dir=$(cd $(basename $1); pwd) shift

config=$1; shift

counter=0

# How many SMTS to run in the node (three smts_server on different ports, each 3 solver and one lemmas server)
# Total process = 50 smts_server + 1 solver_client + 1 lemma_server
n_smts=1

# SMTS Timeout
timeout=1000

# Starting port
port=3000

while [[ $# > 0 ]]; do
    ex=$1;
    bname=`basename $ex`
    script_name=`printf "smts.%s.sh" ${bname}`
    echo $script_name
    cat << __EOF__ > $script_dir/$script_name
#!/bin/bash
## Generated by $0
## From $ex
smts_time=$out_dir/$script_name.smts
output=$out_dir/$script_name

config=${config}
script=${smts_server}

__EOF__

    for ((i=0; i < $n_smts; i++)); do
        if [[ $# == 0 ]]; then
            break;
        fi
        ex=$1; shift
        cat << __EOF__ >> $script_dir/$script_name
 (
  echo $ex;
  inp=/tmp/\$(basename \${script})-`basename $ex .bz2`;
  bunzip2 -c $ex > \${inp};
  sh -c "ulimit -St ${timeout};
  ulimit -Sv 12000000;
  /usr/bin/time -o \${smts_time}.${i}.time -f 'user: %U system: %S wall: %e CPU: %PCPU' python3 \$script -o50 -l -p 3000 -fp \$inp" || true; rm \${inp};
 ) > \$output.${i}.out 2> \$output.${i}.err;
 out_path=\$output.${i}
 result=\$(cat \$out_path.out)
 grep '^;' \$result > /dev/null && (echo \$result >> \$out_path.err; echo error > \$out_path.out) &
__EOF__
    done
    echo "wait" >> $script_dir/$script_name
    counter=$((counter+1))
    chmod +x $script_dir/$script_name
done